source 'https://rubygems.org'

gem 'rails', '3.2.13'

gem 'devise' # authentication

gem "paperclip", "~> 3.4.1" # uploads
gem 'aws-sdk' # access s3 with paperclip
gem 'fog', '~> 1.5.0' # access s3 files

gem 'acts-as-taggable-on' # tags

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :production do
  gem 'pg' # postgresql db
end

group :development do
  gem 'mysql2' # database
  gem "nifty-generators" # layout/helpers generators
  gem 'thin'  # web server: it might be used in production (nginx + thin), don't know what deploy we're going to do
              # if we'll use nginx/apache + pasenger, we don't need it.
end

gem 'gravatar_image_tag' # gravatar support

gem 'imagga' # extract color palette

# TODO: when to use these?
gem 'wordnik'
gem 'flickr_fu'

