development:
  aws:
    key: 'AKIAIDAN3TTMHQNLIPSA'
    secret: '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'
    bucket: 'inspiratio'
    region: 'eu-west-1'

  redis:
    host: 'localhost'
    port: '6379'
    db: '1'

test:
  aws:
    key: ''
    secret: ''
    bucket: ''
    region: 'eu-west-1'

  redis:
    host: 'localhost'
    port: '6379'
    db: '2'

production:
  aws:
    key: 'AKIAIDAN3TTMHQNLIPSA'
    secret: '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'
    bucket: 'inspiratio'
    region: 'eu-west-1'

  redis:
    host: 'localhost'
    port: '6379'
    db: '3'
