development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: inspiratio
  pool: 5
  username: root
  password: ADNJ1807
  socket: localhost:/tmp/mysql.sock
test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: inspiratio
  pool: 5
  username: root
  password: ADNJ1807
  socket: localhost:/tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: **myapp_production**
  pool: 5
  username: **root**
  password: **supersecretpassword**
  socket: **/opt/local/var/run/mysql5/mysqld.sock**